// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repositories;

#nullable disable

namespace TekSan.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20251030084017_init16")]
    partial class init16
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Giyotin Cam Sistemleri",
                            Description = "Giyotin Cam Sistemi Giyotin Cam Sistemi, Teksan All Clean, modern mimariye uyarlanmış en estetik tasarımdır. Bu uzaktan kumandalı sistem, tam panoramik manzaraya",
                            ImageUrl = "assets/img/categories/Giyotin-Cam-Sistemi.jpg",
                            Slug = "giyotin-cam-sistemleri"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Tente Sistemleri",
                            Description = "Tente Sistemleri Fonksiyonel özellikleri ve estetik görüntüsüyle ön plana çıkan Tente modeli, mafsallı tente sınıfının en gelişmiş ve en sağlam Pergola Tente modelidir. Ticari alanlarda veya konutlarda kullanılan pergola tente sistemleri, dış mekanda yaşam kalitesini yükselten ekipmanlardan oluşur. Çok uzun yıllar boyunca kullanılan pergola tente, hava koşullarına karşı en ideal yaşam alanları oluşturmayı sağlar.",
                            ImageUrl = "assets/img/categories/pergola.jpg",
                            Slug = "teksan-tente"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Branda Sistemleri",
                            Description = "Branda Branda çeşitleri, brandaların örnekleri, branda modelleri, istanbul branda, branda fiyatları, balkon brandası, branda kumaşları, Firmamız Yaygın Servis ağı ile oluşacak arıza veya hasar durumunda çadır veya tente sistemine anında müdale fırsatı sunmaktadır. Fiyat bakımından ve kalite bakımından neden uygunuz ? Biz Tente kumaşları toptan şatışı ve bu ürünlerin imalatını.",
                            ImageUrl = "assets/img/categories/kamelya-branda-570x350.jpg",
                            Slug = "branda-sistemleri"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Cam Sistemleri",
                            Description = "Açılır Cam Tavan Sistemleri Açılır Cam Tavan Sistemleri, Kışın yağmur,kar ve rüzgarı dışarıda bırakabileceğiniz, yaz aylarında ise güneşin tadını doyasıya çıkartabileceğiniz bir yaşam alanına sahip olmaya ne dersiniz ? Sabit Cam Tavan (Veranda) uygun malzeme seçeneği Sabit Cam Tavan (Veranda) Sabit cam tavan kış bahçelerine, teras ve balkon üstlerine yapılabilen.",
                            ImageUrl = "assets/img/categories/Acilir-Cam-Tavan-Sistemleri.jpg",
                            Slug = "cam-sistemleri"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Çadır Sistemleri",
                            Description = "Konser tören çadırı gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın daha serin bir hava ortamına sahip olmak için sizlerde bu çadırı yaptırmalısınız. Geniş renk seçeneğimiz ve dayanıklı kumaş modellerimiz ile dilediğiniz her tür marka model brandayı firmamızda bulabilirsiniz. Yapacağımız tüm çalışmalar firmamız tarafından garanti sertifikalı iş teslimatı.",
                            ImageUrl = "assets/img/categories/toren-cadiri.jpg",
                            Slug = "cadır-sistemleri"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Sineklik Sistemleri",
                            Description = "Evlerimizde, ofislerimizde ve yaşam alanlarımızda en çok ihtiyaç duyulan konforlardan biri temiz hava alırken böcek ve haşerelerden korunmaktır. Sineklik sistemleri, estetik görünümleri ve pratik kullanımlarıyla bu ihtiyaca en ideal çözümü sunar.",
                            ImageUrl = "assets/img/categories/istanbul-sineklik-fiyatlari.jpg",
                            Slug = "sineklik-sistemleri"
                        });
                });

            modelBuilder.Entity("Entities.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Media");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltText = "Tente Ürünü 1",
                            ContentType = "image/jpeg",
                            FileName = "Pergole-Tente.jpg",
                            Url = "/assets/img/properties/Pergole-Tente.jpg"
                        },
                        new
                        {
                            Id = 2,
                            AltText = "Tente Ürünü 2",
                            ContentType = "image/jpeg",
                            FileName = "Pergole-Tente-2.jpg",
                            Url = "/assets/img/properties/Pergole-Tente-2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            AltText = "Service ilk resim",
                            ContentType = "image/jpeg",
                            FileName = "service-2.jpg",
                            Url = "/assets/img/service/service-2.jpg"
                        },
                        new
                        {
                            Id = 4,
                            AltText = "koruktentekapak",
                            ContentType = "image/jpeg",
                            FileName = "koruktente-1.jpg",
                            Url = "/assets/img/properties/koruktente-1.jpg"
                        },
                        new
                        {
                            Id = 5,
                            AltText = "koruktente-2",
                            ContentType = "image/jpeg",
                            FileName = "koruktente-2.jpg",
                            Url = "/assets/img/properties/koruktente-2.jpg"
                        },
                        new
                        {
                            Id = 6,
                            AltText = "koruktente-3",
                            ContentType = "image/jpeg",
                            FileName = "koruktente-3.jpg",
                            Url = "/assets/img/properties/koruktente-3.jpg"
                        },
                        new
                        {
                            Id = 7,
                            AltText = "koruktente-4",
                            ContentType = "image/jpeg",
                            FileName = "koruktente-4.jpg",
                            Url = "/assets/img/properties/koruktente-4.jpg"
                        },
                        new
                        {
                            Id = 8,
                            AltText = "koruktente-5",
                            ContentType = "image/jpeg",
                            FileName = "koruktente-5.jpg",
                            Url = "/assets/img/properties/koruktente-5.jpg"
                        },
                        new
                        {
                            Id = 9,
                            AltText = "Pergole-Tente-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "Pergole-1.jpg",
                            Url = "/assets/img/properties/Pergole-Tente-1.jpg"
                        },
                        new
                        {
                            Id = 10,
                            AltText = "Pergole-Tente-3.jpg",
                            ContentType = "image/jpeg",
                            FileName = "Pergole-3.jpg",
                            Url = "/assets/img/properties/Pergole-Tente-3.jpg"
                        },
                        new
                        {
                            Id = 11,
                            AltText = "Pergole-Tente-4.jpg",
                            ContentType = "image/jpeg",
                            FileName = "Pergole-4.jpg",
                            Url = "/assets/img/properties/Pergole-Tente-4.jpg"
                        },
                        new
                        {
                            Id = 12,
                            AltText = "Pergole-Tente-5.jpg",
                            ContentType = "image/jpeg",
                            FileName = "Pergole-5.jpg",
                            Url = "/assets/img/properties/Pergole-Tente-5.jpg"
                        },
                        new
                        {
                            Id = 13,
                            AltText = "stor-tente-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "stor-tente-1.jpg",
                            Url = "/assets/img/properties/stor-tente-1.jpg"
                        },
                        new
                        {
                            Id = 14,
                            AltText = "stor-tente-2.jpg",
                            ContentType = "image/jpeg",
                            FileName = "stor-tente-2.jpg",
                            Url = "/assets/img/properties/stor-tente-2.jpg"
                        },
                        new
                        {
                            Id = 15,
                            AltText = "stor-tente-3.jpg",
                            ContentType = "image/jpeg",
                            FileName = "stor-tente-3.jpg",
                            Url = "/assets/img/properties/stor-tente-3.jpg"
                        },
                        new
                        {
                            Id = 16,
                            AltText = "stor-tente-4.jpg",
                            ContentType = "image/jpeg",
                            FileName = "stor-tente-4.jpg",
                            Url = "/assets/img/properties/stor-tente-4.jpg"
                        },
                        new
                        {
                            Id = 17,
                            AltText = "cift-acilir-tente-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "cift-acilir-tente-1.jpg",
                            Url = "/assets/img/properties/cift-acilir-tente-1.jpg"
                        },
                        new
                        {
                            Id = 18,
                            AltText = "cift-acilir-tente-2.jpg",
                            ContentType = "image/jpeg",
                            FileName = "cift-acilir-tente-2.jpg",
                            Url = "/assets/img/properties/cift-acilir-tente-2.jpg"
                        },
                        new
                        {
                            Id = 19,
                            AltText = "cift-acilir-tente-3.jpg",
                            ContentType = "image/jpeg",
                            FileName = "cift-acilir-tente-3.jpg",
                            Url = "/assets/img/properties/cift-acilir-tente-3.jpg"
                        },
                        new
                        {
                            Id = 20,
                            AltText = "cift-acilir-tente-4.jpg",
                            ContentType = "image/jpeg",
                            FileName = "cift-acilir-tente-4.jpg",
                            Url = "/assets/img/properties/cift-acilir-tente-4.jpg"
                        },
                        new
                        {
                            Id = 21,
                            AltText = "mafsal-tente-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "mafsal-tente-1.jpg",
                            Url = "/assets/img/properties/mafsal-tente-1.jpg"
                        },
                        new
                        {
                            Id = 22,
                            AltText = "mafsal-tente-2.jpg",
                            ContentType = "image/jpeg",
                            FileName = "mafsal-tente-2.jpg",
                            Url = "/assets/img/properties/mafsal-tente-2.jpg"
                        },
                        new
                        {
                            Id = 23,
                            AltText = "mafsal-tente-3.jpg",
                            ContentType = "image/jpeg",
                            FileName = "mafsal-tente-3.jpg",
                            Url = "/assets/img/properties/mafsal-tente-3.jpg"
                        },
                        new
                        {
                            Id = 24,
                            AltText = "mafsal-tente-4.jpg",
                            ContentType = "image/jpeg",
                            FileName = "mafsal-tente-4.jpg",
                            Url = "/assets/img/properties/mafsal-tente-4.jpg"
                        },
                        new
                        {
                            Id = 25,
                            AltText = "giyotin-cam-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "giyotin-cam-1.jpg",
                            Url = "/assets/img/properties/giyotin-cam-1.jpg"
                        },
                        new
                        {
                            Id = 26,
                            AltText = "giyotin-cam-2.jpg",
                            ContentType = "image/jpeg",
                            FileName = "giyotin-cam-2.jpg",
                            Url = "/assets/img/properties/giyotin-cam-2.jpg"
                        },
                        new
                        {
                            Id = 27,
                            AltText = "giyotin-cam-3.jpg",
                            ContentType = "image/jpeg",
                            FileName = "giyotin-cam-3.jpg",
                            Url = "/assets/img/properties/giyotin-cam-3.jpg"
                        },
                        new
                        {
                            Id = 28,
                            AltText = "giyotin-cam-4.jpg",
                            ContentType = "image/jpeg",
                            FileName = "giyotin-cam-4.jpg",
                            Url = "/assets/img/properties/giyotin-cam-4.jpg"
                        },
                        new
                        {
                            Id = 29,
                            AltText = "fotoselli-kapi-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "fotoselli-kapi-1.jpg",
                            Url = "/assets/img/properties/fotoselli-kapi-1.jpg"
                        },
                        new
                        {
                            Id = 30,
                            AltText = "fotoselli-kapi-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "fotoselli-kapi-2.jpg",
                            Url = "/assets/img/properties/fotoselli-kapi-2.jpg"
                        },
                        new
                        {
                            Id = 31,
                            AltText = "fotoselli-kapi-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "fotoselli-kapi-3.jpg",
                            Url = "/assets/img/properties/fotoselli-kapi-3.jpg"
                        },
                        new
                        {
                            Id = 32,
                            AltText = "fotoselli-kapi-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "fotoselli-kapi-4.jpg",
                            Url = "/assets/img/properties/fotoselli-kapi-4.jpg"
                        },
                        new
                        {
                            Id = 33,
                            AltText = "kis-bahcecileri-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "kis-bahcecileri-1.jpg",
                            Url = "/assets/img/properties/kis-bahcecileri-1.jpg"
                        },
                        new
                        {
                            Id = 34,
                            AltText = "kis-bahcecileri-2.jpg",
                            ContentType = "image/jpeg",
                            FileName = "kis-bahcecileri-2.jpg",
                            Url = "/assets/img/properties/kis-bahcecileri-2.jpg"
                        },
                        new
                        {
                            Id = 35,
                            AltText = "kis-bahcecileri-3.jpg",
                            ContentType = "image/jpeg",
                            FileName = "kis-bahcecileri-3.jpg",
                            Url = "/assets/img/properties/kis-bahcecileri-3.jpg"
                        },
                        new
                        {
                            Id = 36,
                            AltText = "kis-bahcecileri-4.jpg",
                            ContentType = "image/jpeg",
                            FileName = "kis-bahcecileri-4.jpg",
                            Url = "/assets/img/properties/kis-bahcecileri-4.jpg"
                        },
                        new
                        {
                            Id = 37,
                            AltText = "seffaf-alan-kapama-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "seffaf-alan-kapama-1.jpg",
                            Url = "/assets/img/properties/seffaf-alan-kapama-1.jpg"
                        },
                        new
                        {
                            Id = 38,
                            AltText = "seffaf-alan-kapama-2.jpg",
                            ContentType = "image/jpeg",
                            FileName = "seffaf-alan-kapama-2.jpg",
                            Url = "/assets/img/properties/seffaf-alan-kapama-2.jpg"
                        },
                        new
                        {
                            Id = 39,
                            AltText = "seffaf-alan-kapama-3.jpg",
                            ContentType = "image/jpeg",
                            FileName = "seffaf-alan-kapama-3.jpg",
                            Url = "/assets/img/properties/seffaf-alan-kapama-3.jpg"
                        },
                        new
                        {
                            Id = 40,
                            AltText = "seffaf-alan-kapama-4.jpg",
                            ContentType = "image/jpeg",
                            FileName = "seffaf-alan-kapama-4.jpg",
                            Url = "/assets/img/properties/seffaf-alan-kapama-4.jpg"
                        },
                        new
                        {
                            Id = 41,
                            AltText = "seffaf-branda-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "seffaf-branda-1.jpg",
                            Url = "/assets/img/properties/seffaf-alan-kapama-4.jpg"
                        },
                        new
                        {
                            Id = 42,
                            AltText = "seffaf-branda-2.jpg",
                            ContentType = "image/jpeg",
                            FileName = "seffaf-branda-2.jpg",
                            Url = "/assets/img/properties/seffaf-alan-kapama-4.jpg"
                        },
                        new
                        {
                            Id = 43,
                            AltText = "seffaf-branda-3.jpg",
                            ContentType = "image/jpeg",
                            FileName = "seffaf-branda-3.jpg",
                            Url = "/assets/img/properties/seffaf-alan-kapama-4.jpg"
                        },
                        new
                        {
                            Id = 44,
                            AltText = "seffaf-branda-4.jpg",
                            ContentType = "image/jpeg",
                            FileName = "seffaf-branda-4.jpg",
                            Url = "/assets/img/properties/seffaf-alan-kapama-4.jpg"
                        },
                        new
                        {
                            Id = 45,
                            AltText = "havuz-brandasi-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "havuz-brandasi-1.jpg",
                            Url = "/assets/img/properties/havuz-brandasi-1.jpg"
                        },
                        new
                        {
                            Id = 46,
                            AltText = "havuz-brandasi-2.jpg",
                            ContentType = "image/jpeg",
                            FileName = "havuz-brandasi-2.jpg",
                            Url = "/assets/img/properties/havuz-brandasi-2.jpg"
                        },
                        new
                        {
                            Id = 47,
                            AltText = "havuz-brandasi-3.jpg",
                            ContentType = "image/jpeg",
                            FileName = "havuz-brandasi-3.jpg",
                            Url = "/assets/img/properties/havuz-brandasi-3.jpg"
                        },
                        new
                        {
                            Id = 48,
                            AltText = "havuz-brandasi-4.jpg",
                            ContentType = "image/jpeg",
                            FileName = "havuz-brandasi-4.jpg",
                            Url = "/assets/img/properties/havuz-brandasi-4.jpg"
                        },
                        new
                        {
                            Id = 49,
                            AltText = "iskele-branda-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "iskele-branda-1.jpg",
                            Url = "/assets/img/properties/iskele-branda-1.jpg"
                        },
                        new
                        {
                            Id = 50,
                            AltText = "iskele-branda-2.jpg",
                            ContentType = "image/jpeg",
                            FileName = "iskele-branda-2.jpg",
                            Url = "/assets/img/properties/iskele-branda-2.jpg"
                        },
                        new
                        {
                            Id = 51,
                            AltText = "iskele-branda-3.jpg",
                            ContentType = "image/jpeg",
                            FileName = "iskele-branda-3.jpg",
                            Url = "/assets/img/properties/iskele-branda-3.jpg"
                        },
                        new
                        {
                            Id = 52,
                            AltText = "iskele-branda-4.jpg",
                            ContentType = "image/jpeg",
                            FileName = "iskele-branda-4.jpg",
                            Url = "/assets/img/properties/iskele-branda-4.jpg"
                        },
                        new
                        {
                            Id = 53,
                            AltText = "kamleya-brandasi-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "kamleya-brandasi-1.jpg",
                            Url = "/assets/img/properties/kamleya-brandasi-1.jpg"
                        },
                        new
                        {
                            Id = 54,
                            AltText = "kamleya-brandasi-2.jpg",
                            ContentType = "image/jpeg",
                            FileName = "kamleya-brandasi-2.jpg",
                            Url = "/assets/img/properties/kamleya-brandasi-2.jpg"
                        },
                        new
                        {
                            Id = 55,
                            AltText = "kamleya-brandasi-3.jpg",
                            ContentType = "image/jpeg",
                            FileName = "kamleya-brandasi-3.jpg",
                            Url = "/assets/img/properties/kamleya-brandasi-3.jpg"
                        },
                        new
                        {
                            Id = 56,
                            AltText = "kamleya-brandasi-4.jpg",
                            ContentType = "image/jpeg",
                            FileName = "kamleya-brandasi-4.jpg",
                            Url = "/assets/img/properties/kamleya-brandasi-4.jpg"
                        },
                        new
                        {
                            Id = 57,
                            AltText = "pazar-cadir-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "pazar-cadir-1.jpg",
                            Url = "/assets/img/properties/pazar-cadir-1.jpg"
                        },
                        new
                        {
                            Id = 58,
                            AltText = "pazar-cadir-2.jpg",
                            ContentType = "image/jpeg",
                            FileName = "pazar-cadir-2.jpg",
                            Url = "/assets/img/properties/pazar-cadir-2.jpg"
                        },
                        new
                        {
                            Id = 59,
                            AltText = "pazar-cadir-3.jpg",
                            ContentType = "image/jpeg",
                            FileName = "pazar-cadir-3.jpg",
                            Url = "/assets/img/properties/pazar-cadir-3.jpg"
                        },
                        new
                        {
                            Id = 60,
                            AltText = "reklam-afisi-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "reklam-afisi-1.jpg",
                            Url = "/assets/img/properties/reklam-afisi-1.jpg"
                        },
                        new
                        {
                            Id = 61,
                            AltText = "reklam-afisi-2.jpg",
                            ContentType = "image/jpeg",
                            FileName = "reklam-afisi-2.jpg",
                            Url = "/assets/img/properties/reklam-afisi-2.jpg"
                        },
                        new
                        {
                            Id = 62,
                            AltText = "reklam-afisi-3.jpg",
                            ContentType = "image/jpeg",
                            FileName = "reklam-afisi-3.jpg",
                            Url = "/assets/img/properties/reklam-afisi-3.jpg"
                        },
                        new
                        {
                            Id = 63,
                            AltText = "reklam-afisi-4.jpg",
                            ContentType = "image/jpeg",
                            FileName = "reklam-afisi-4.jpg",
                            Url = "/assets/img/properties/reklam-afisi-4.jpg"
                        },
                        new
                        {
                            Id = 64,
                            AltText = "arac-korumalari-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "arac-korumalari-1.jpg",
                            Url = "/assets/img/properties/arac-korumalari-1.jpg"
                        },
                        new
                        {
                            Id = 65,
                            AltText = "arac-korumalari-2.jpg",
                            ContentType = "image/jpeg",
                            FileName = "arac-korumalari-2.jpg",
                            Url = "/assets/img/properties/arac-korumalari-2.jpg"
                        },
                        new
                        {
                            Id = 66,
                            AltText = "arac-korumalari-3.jpg",
                            ContentType = "image/jpeg",
                            FileName = "arac-korumalari-3.jpg",
                            Url = "/assets/img/properties/arac-korumalari-3.jpg"
                        },
                        new
                        {
                            Id = 67,
                            AltText = "yat-brandasi-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "yat-brandasi-1.jpg",
                            Url = "/assets/img/properties/yat-brandasi-1.jpg"
                        },
                        new
                        {
                            Id = 68,
                            AltText = "yat-brandasi-2.jpg",
                            ContentType = "image/jpeg",
                            FileName = "yat-brandasi-2.jpg",
                            Url = "/assets/img/properties/yat-brandasi-2.jpg"
                        },
                        new
                        {
                            Id = 69,
                            AltText = "yat-brandasi-3.jpg",
                            ContentType = "image/jpeg",
                            FileName = "yat-brandasi-3.jpg",
                            Url = "/assets/img/properties/yat-brandasi-3.jpg"
                        },
                        new
                        {
                            Id = 70,
                            AltText = "cam-balkon-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "cam-balkon-1.jpg",
                            Url = "/assets/img/properties/cam-balkon-1.jpg"
                        },
                        new
                        {
                            Id = 71,
                            AltText = "cam-balkon-2.jpg",
                            ContentType = "image/jpeg",
                            FileName = "cam-balkon-2.jpg",
                            Url = "/assets/img/properties/cam-balkon-2.jpg"
                        },
                        new
                        {
                            Id = 72,
                            AltText = "cam-balkon-3.jpg",
                            ContentType = "image/jpeg",
                            FileName = "cam-balkon-3.jpg",
                            Url = "/assets/img/properties/cam-balkon-3.jpg"
                        },
                        new
                        {
                            Id = 73,
                            AltText = "cam-balkon-4.jpg",
                            ContentType = "image/jpeg",
                            FileName = "cam-balkon-4.jpg",
                            Url = "/assets/img/properties/cam-balkon-4.jpg"
                        },
                        new
                        {
                            Id = 74,
                            AltText = "cam-balkon-5.jpg",
                            ContentType = "image/jpeg",
                            FileName = "cam-balkon-5.jpg",
                            Url = "/assets/img/properties/cam-balkon-5.jpg"
                        },
                        new
                        {
                            Id = 75,
                            AltText = "cam-balkon-6.jpg",
                            ContentType = "image/jpeg",
                            FileName = "cam-balkon-6.jpg",
                            Url = "/assets/img/properties/cam-balkon-6.jpg"
                        },
                        new
                        {
                            Id = 76,
                            AltText = "cam-veranda-1",
                            ContentType = "image/jpeg",
                            FileName = "cam-veranda-1.jpg",
                            Url = "/assets/img/properties/cam-veranda-1.jpg"
                        },
                        new
                        {
                            Id = 77,
                            AltText = "cam-veranda-2",
                            ContentType = "image/jpeg",
                            FileName = "cam-veranda-2.jpg",
                            Url = "/assets/img/properties/cam-veranda-2.jpg"
                        },
                        new
                        {
                            Id = 78,
                            AltText = "cam-veranda-3",
                            ContentType = "image/jpeg",
                            FileName = "cam-veranda-3.jpg",
                            Url = "/assets/img/properties/cam-veranda-3.jpg"
                        },
                        new
                        {
                            Id = 79,
                            AltText = "cam-veranda-4",
                            ContentType = "image/jpeg",
                            FileName = "cam-veranda-4.jpg",
                            Url = "/assets/img/properties/cam-veranda-4.jpg"
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Comment = "Pergole Tenteler Ticari alanlarda veya konutlarda kullanılan pergole tente sistemleri, dış mekanda yaşam kalitesini yükselten ekipmanlardan oluşur. Çok uzun yıllar boyunca kullanılan pergole tente, hava koşullarına karşı en ideal yaşam alanları oluşturmayı sağlar. Bu sistemler teknolojik gelişmelerle birlikte güncellenip motor ve sensör desteğiyle daha kullanışlı hale gelmiştir. İşyeriniz veya eviniz için ihtiyacınız olan tüm pergola tenteleri firmamızdan uygun fiyatlarla tedarik edebilirsiniz. ",
                            Name = "Pergole Tente",
                            Price = 2000m,
                            Slug = "pergole-tente"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Comment = "Körüklü tentelerin kurulumu ve kullanıma kolay tente modellerinden sadece biridir. Tente Sistemi Akordeon Şeklinde Açılıp Kapanmaktadır Diğer Tentelerde Farkı yan kısımlar Kapalı olduğundan Güneş ve Yağmur gelmesini Engeller  kullanıldığı alanlarda şık Dizaynı ve Tasarımıyla bulunduğu alana ayrı bir Görsellik katar.\r\n\r\nKörüklü Sisteminin Saçak Modeli Deniz dalgası modeli veya Düz saçak modeli tercih edilmektedir.",
                            Name = "Körük Tente",
                            Price = 2500m,
                            Slug = "koruk-tente"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Comment = "Stor tente normal mafsallı tentenin kolsuz modelidir.karşıdan gelen güneş için tercih edilen bir modeldir. Stor tente Yukardan aşağı açılıp kapanan bir modeldir istenildiği taktirde motorlu sistemde uyumludur.stor tente asıl amacı, gölgelendirme işlevini yapmak olsa da fonksiyonellik yönünden de hiçbir şekilde sınır tanımamaktadır.",
                            Name = "Stor Tente",
                            Price = 1500m,
                            Slug = "stor-tente"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Comment = "Çift açılır tente kurulumu ve kullanımı kolay tente modellerinden sadece biridir.\r\n\r\nBu tente sayesinde hem daha sağlıklı bir hava ortamına sahip olursunuz hemde iş yerleriniz daha güzel bire görünüme kavuşmaktadır. taksitli fiyatları akrilik kumaşlı ısı geçirmeyen garanti belgeli kaliteli",
                            Name = "Çift Açılır Tente",
                            Price = 5000m,
                            Slug = "cift-acılır-tente"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Mafsallı Tente",
                            Price = 30000m,
                            Slug = "mafsalli-tente"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Giyotin Cam",
                            Price = 30000m,
                            Slug = "giyotin-cam"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Fotoselli Giyotin Cam Kapı",
                            Price = 30000m,
                            Slug = "fotoselli-giyotin-cam-kapi"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Şeffaf Kış Bahçesi",
                            Price = 30000m,
                            Slug = "seffaf-kıs-bahcesi"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Şeffaf Alan Kapama",
                            Price = 30000m,
                            Slug = "seffaf-alan-kapama"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Şeffaf Pvc Mika Branda",
                            Price = 30000m,
                            Slug = "seffaf-pvc-mika-branda"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Havuz Brandası",
                            Price = 30000m,
                            Slug = "havuz-brandasi"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "İskele Brandası",
                            Price = 30000m,
                            Slug = "iskele-brandasi"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Kamelya Branda",
                            Price = 30000m,
                            Slug = "kamelya-branda"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Pazar Brandası",
                            Price = 30000m,
                            Slug = "pazar-brandasi"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Reklam Brandası",
                            Price = 30000m,
                            Slug = "reklam-brandasi"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Araç Koruma Brandası",
                            Price = 30000m,
                            Slug = "arac-koruma-brandasi"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Yat ve Tekne Brandası",
                            Price = 30000m,
                            Slug = "yat-tekne-brandasi"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Cam Balkon",
                            Price = 30000m,
                            Slug = "cam-balkon"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Cam Veranda",
                            Price = 30000m,
                            Slug = "cam-veranda"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Depo Çadırı",
                            Price = 30000m,
                            Slug = "depo-cadiri"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Doğal Afet Çadırı",
                            Price = 30000m,
                            Slug = "dogal-afet-cadiri"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Halı Saha Çadırı",
                            Price = 30000m,
                            Slug = "hali -saha-cadiri"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Hayvan Besi Çadırı",
                            Price = 30000m,
                            Slug = "hayvan-besi-cadiri"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Spor Kompleksi Çadırı",
                            Price = 30000m,
                            Slug = "spor-kompleksi-cadiri"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Şantiye Çadırı",
                            Price = 30000m,
                            Slug = "santiye-cadiri"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Kiralık Çadır",
                            Price = 30000m,
                            Slug = "kiralik-cadir"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Konser Tören Çadırı",
                            Price = 30000m,
                            Slug = "konser-toren-cadiri"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 6,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Sürgülü Sineklik",
                            Price = 30000m,
                            Slug = "surgulu-sineklik"
                        });
                });

            modelBuilder.Entity("Entities.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsMain = true,
                            MediaId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsMain = false,
                            MediaId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 4,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 5,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 6,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 7,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 8,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 9,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 10,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 11,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 12,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 13,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 14,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 15,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 16,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 17,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 18,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 19,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 20,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 21,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 22,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 23,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 24,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 25,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 26,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 27,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 28,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 29,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 30,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 30,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 31,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 31,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 32,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 32,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 33,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 34,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 34,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 35,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 35,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 36,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 36,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 37,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 37,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 38,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 38,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 39,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 39,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 40,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 40,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 41,
                            ProductId = 10
                        },
                        new
                        {
                            Id = 41,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 42,
                            ProductId = 10
                        },
                        new
                        {
                            Id = 42,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 43,
                            ProductId = 10
                        },
                        new
                        {
                            Id = 43,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 44,
                            ProductId = 10
                        },
                        new
                        {
                            Id = 44,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 45,
                            ProductId = 11
                        },
                        new
                        {
                            Id = 45,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 46,
                            ProductId = 11
                        },
                        new
                        {
                            Id = 46,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 47,
                            ProductId = 11
                        },
                        new
                        {
                            Id = 47,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 48,
                            ProductId = 11
                        },
                        new
                        {
                            Id = 48,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 49,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 49,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 50,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 50,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 51,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 51,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 52,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 52,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 53,
                            ProductId = 13
                        },
                        new
                        {
                            Id = 53,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 54,
                            ProductId = 13
                        },
                        new
                        {
                            Id = 54,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 55,
                            ProductId = 13
                        },
                        new
                        {
                            Id = 55,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 56,
                            ProductId = 13
                        },
                        new
                        {
                            Id = 56,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 57,
                            ProductId = 14
                        },
                        new
                        {
                            Id = 57,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 58,
                            ProductId = 14
                        },
                        new
                        {
                            Id = 58,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 59,
                            ProductId = 14
                        },
                        new
                        {
                            Id = 59,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 60,
                            ProductId = 15
                        },
                        new
                        {
                            Id = 60,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 61,
                            ProductId = 15
                        },
                        new
                        {
                            Id = 61,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 62,
                            ProductId = 15
                        },
                        new
                        {
                            Id = 62,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 63,
                            ProductId = 15
                        },
                        new
                        {
                            Id = 63,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 64,
                            ProductId = 16
                        },
                        new
                        {
                            Id = 64,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 65,
                            ProductId = 16
                        },
                        new
                        {
                            Id = 65,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 66,
                            ProductId = 16
                        },
                        new
                        {
                            Id = 66,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 67,
                            ProductId = 17
                        },
                        new
                        {
                            Id = 67,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 68,
                            ProductId = 17
                        },
                        new
                        {
                            Id = 68,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 69,
                            ProductId = 17
                        },
                        new
                        {
                            Id = 69,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 70,
                            ProductId = 18
                        },
                        new
                        {
                            Id = 70,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 71,
                            ProductId = 18
                        },
                        new
                        {
                            Id = 71,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 72,
                            ProductId = 18
                        },
                        new
                        {
                            Id = 72,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 73,
                            ProductId = 18
                        },
                        new
                        {
                            Id = 73,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 74,
                            ProductId = 18
                        },
                        new
                        {
                            Id = 74,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 75,
                            ProductId = 18
                        },
                        new
                        {
                            Id = 75,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 76,
                            ProductId = 19
                        },
                        new
                        {
                            Id = 76,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 77,
                            ProductId = 19
                        },
                        new
                        {
                            Id = 77,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 78,
                            ProductId = 19
                        },
                        new
                        {
                            Id = 78,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 79,
                            ProductId = 19
                        });
                });

            modelBuilder.Entity("Entities.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Firmamız satış dışında Teknik Servisleri montaj hizmeti de vermektedir. Ayrıca kurulmuş olan yapıları yeni yerinize en uygun şekilde uyarlayarak kurulum hizmetini de sunmaktayız.",
                            Name = "Teknik Servis",
                            Slug = "teknik-servis"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Firmamız satış dışında Teknik Servisleri montaj hizmeti de vermektedir. Ayrıca kurulmuş olan yapıları yeni yerinize en uygun şekilde uyarlayarak kurulum hizmetini de sunmaktayız.",
                            Name = "Teknik Özellikler",
                            Slug = "teknik-ozellikler"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Firmamız satış dışında Teknik Servisleri montaj hizmeti de vermektedir. Ayrıca kurulmuş olan yapıları yeni yerinize en uygun şekilde uyarlayarak kurulum hizmetini de sunmaktayız.",
                            Name = "Blackout Pergola Tente Kumaşı",
                            ParentId = 2,
                            Slug = "blackout-pergola-tente-kumasi"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Firmamız satış dışında Teknik Servisleri montaj hizmeti de vermektedir. Ayrıca kurulmuş olan yapıları yeni yerinize en uygun şekilde uyarlayarak kurulum hizmetini de sunmaktayız.",
                            Name = "Pergola Tente Teknik Özellikleri",
                            ParentId = 2,
                            Slug = "pergola-tente-teknik-ozellikleri"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Firmamız satış dışında Teknik Servisleri montaj hizmeti de vermektedir. Ayrıca kurulmuş olan yapıları yeni yerinize en uygun şekilde uyarlayarak kurulum hizmetini de sunmaktayız.",
                            Name = "Pergola Tente İmalatı Çeşitleri",
                            ParentId = 2,
                            Slug = "pergola-tente-imalati-cesitleri"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Firmamız satış dışında Teknik Servisleri montaj hizmeti de vermektedir. Ayrıca kurulmuş olan yapıları yeni yerinize en uygun şekilde uyarlayarak kurulum hizmetini de sunmaktayız.",
                            Name = "Kullanım Özellikleri",
                            Slug = "kullanim-ozellikleri"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Firmamız satış dışında Teknik Servisleri montaj hizmeti de vermektedir. Ayrıca kurulmuş olan yapıları yeni yerinize en uygun şekilde uyarlayarak kurulum hizmetini de sunmaktayız.",
                            Name = "Projeler",
                            Slug = "projeler"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Firmamız satış dışında Teknik Servisleri montaj hizmeti de vermektedir. Ayrıca kurulmuş olan yapıları yeni yerinize en uygun şekilde uyarlayarak kurulum hizmetini de sunmaktayız.",
                            Name = "Faydalı Bilgiler",
                            Slug = "faydali-bilgiler"
                        });
                });

            modelBuilder.Entity("Entities.Models.ServiceImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MediaId = 3,
                            ServiceId = 1
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Models.ProductImage", b =>
                {
                    b.HasOne("Entities.Models.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Models.Service", b =>
                {
                    b.HasOne("Entities.Models.Service", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Entities.Models.ServiceImage", b =>
                {
                    b.HasOne("Entities.Models.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Service", "Service")
                        .WithMany("Images")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Entities.Models.Service", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
