// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repositories;

#nullable disable

namespace TekSan.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20251025202551_init5")]
    partial class init5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Giyotin Cam Sistemleri",
                            Description = "Giyotin Cam Sistemi Giyotin Cam Sistemi, Teksan All Clean, modern mimariye uyarlanmış en estetik tasarımdır. Bu uzaktan kumandalı sistem, tam panoramik manzaraya",
                            ImageUrl = "assets/img/categories/Giyotin-Cam-Sistemi.jpg",
                            Slug = "giyotin-cam-sistemleri"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Tente Sistemleri",
                            Description = "Tente Sistemleri Fonksiyonel özellikleri ve estetik görüntüsüyle ön plana çıkan Tente modeli, mafsallı tente sınıfının en gelişmiş ve en sağlam Pergola Tente modelidir. Ticari alanlarda veya konutlarda kullanılan pergola tente sistemleri, dış mekanda yaşam kalitesini yükselten ekipmanlardan oluşur. Çok uzun yıllar boyunca kullanılan pergola tente, hava koşullarına karşı en ideal yaşam alanları oluşturmayı sağlar.",
                            ImageUrl = "assets/img/categories/pergola.jpg",
                            Slug = "teksan-tente"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Branda Sistemleri",
                            Description = "Branda Branda çeşitleri, brandaların örnekleri, branda modelleri, istanbul branda, branda fiyatları, balkon brandası, branda kumaşları, Firmamız Yaygın Servis ağı ile oluşacak arıza veya hasar durumunda çadır veya tente sistemine anında müdale fırsatı sunmaktadır. Fiyat bakımından ve kalite bakımından neden uygunuz ? Biz Tente kumaşları toptan şatışı ve bu ürünlerin imalatını.",
                            ImageUrl = "assets/img/categories/kamelya-branda-570x350.jpg",
                            Slug = "branda-sistemleri"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Cam Sistemleri",
                            Description = "Açılır Cam Tavan Sistemleri Açılır Cam Tavan Sistemleri, Kışın yağmur,kar ve rüzgarı dışarıda bırakabileceğiniz, yaz aylarında ise güneşin tadını doyasıya çıkartabileceğiniz bir yaşam alanına sahip olmaya ne dersiniz ? Sabit Cam Tavan (Veranda) uygun malzeme seçeneği Sabit Cam Tavan (Veranda) Sabit cam tavan kış bahçelerine, teras ve balkon üstlerine yapılabilen.",
                            ImageUrl = "assets/img/categories/Acilir-Cam-Tavan-Sistemleri.jpg",
                            Slug = "cam-sistemleri"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Çadır Sistemleri",
                            Description = "Konser tören çadırı gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın daha serin bir hava ortamına sahip olmak için sizlerde bu çadırı yaptırmalısınız. Geniş renk seçeneğimiz ve dayanıklı kumaş modellerimiz ile dilediğiniz her tür marka model brandayı firmamızda bulabilirsiniz. Yapacağımız tüm çalışmalar firmamız tarafından garanti sertifikalı iş teslimatı.",
                            ImageUrl = "assets/img/categories/toren-cadiri.jpg",
                            Slug = "cadır-sistemleri"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Sineklik Sistemleri",
                            Description = "Evlerimizde, ofislerimizde ve yaşam alanlarımızda en çok ihtiyaç duyulan konforlardan biri temiz hava alırken böcek ve haşerelerden korunmaktır. Sineklik sistemleri, estetik görünümleri ve pratik kullanımlarıyla bu ihtiyaca en ideal çözümü sunar.",
                            ImageUrl = "assets/img/categories/istanbul-sineklik-fiyatlari.jpg",
                            Slug = "sineklik-sistemleri"
                        });
                });

            modelBuilder.Entity("Entities.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Media");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltText = "Tente Ürünü 1",
                            ContentType = "image/jpeg",
                            FileName = "Pergole-Tente.jpg",
                            Url = "/assets/img/properties/Pergole-Tente.jpg"
                        },
                        new
                        {
                            Id = 2,
                            AltText = "Tente Ürünü 2",
                            ContentType = "image/jpeg",
                            FileName = "Pergole-Tente-2.jpg",
                            Url = "/assets/img/properties/Pergole-Tente-2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            AltText = "Service ilk resim",
                            ContentType = "image/jpeg",
                            FileName = "service-2.jpg",
                            Url = "/assets/img/service/service-2.jpg"
                        },
                        new
                        {
                            Id = 4,
                            AltText = "koruktentekapak",
                            ContentType = "image/jpeg",
                            FileName = "koruktente-1.jpg",
                            Url = "/assets/img/properties/koruktente-1.jpg"
                        },
                        new
                        {
                            Id = 5,
                            AltText = "koruktente-2",
                            ContentType = "image/jpeg",
                            FileName = "koruktente-2.jpg",
                            Url = "/assets/img/properties/koruktente-2.jpg"
                        },
                        new
                        {
                            Id = 6,
                            AltText = "koruktente-3",
                            ContentType = "image/jpeg",
                            FileName = "koruktente-3.jpg",
                            Url = "/assets/img/properties/koruktente-3.jpg"
                        },
                        new
                        {
                            Id = 7,
                            AltText = "koruktente-4",
                            ContentType = "image/jpeg",
                            FileName = "koruktente-4.jpg",
                            Url = "/assets/img/properties/koruktente-4.jpg"
                        },
                        new
                        {
                            Id = 8,
                            AltText = "koruktente-5",
                            ContentType = "image/jpeg",
                            FileName = "koruktente-5.jpg",
                            Url = "/assets/img/properties/koruktente-5.jpg"
                        },
                        new
                        {
                            Id = 9,
                            AltText = "Pergole-1.jpg",
                            ContentType = "image/jpeg",
                            FileName = "Pergole-1.jpg",
                            Url = "/assets/img/properties/Pergole-1.jpg"
                        },
                        new
                        {
                            Id = 10,
                            AltText = "Pergole-3.jpg",
                            ContentType = "image/jpeg",
                            FileName = "Pergole-3.jpg",
                            Url = "/assets/img/properties/Pergole-3.jpg"
                        },
                        new
                        {
                            Id = 11,
                            AltText = "Pergole-4.jpg",
                            ContentType = "image/jpeg",
                            FileName = "Pergole-4.jpg",
                            Url = "/assets/img/properties/Pergole-4.jpg"
                        },
                        new
                        {
                            Id = 12,
                            AltText = "Pergole-5.jpg",
                            ContentType = "image/jpeg",
                            FileName = "Pergole-5.jpg",
                            Url = "/assets/img/properties/Pergole-5.jpg"
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Comment = "Pergole Tenteler Ticari alanlarda veya konutlarda kullanılan pergole tente sistemleri, dış mekanda yaşam kalitesini yükselten ekipmanlardan oluşur. Çok uzun yıllar boyunca kullanılan pergole tente, hava koşullarına karşı en ideal yaşam alanları oluşturmayı sağlar. Bu sistemler teknolojik gelişmelerle birlikte güncellenip motor ve sensör desteğiyle daha kullanışlı hale gelmiştir. İşyeriniz veya eviniz için ihtiyacınız olan tüm pergola tenteleri firmamızdan uygun fiyatlarla tedarik edebilirsiniz. ",
                            Name = "Pergole Tente",
                            Price = 2000m,
                            Slug = "pergole-tente"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Comment = "Körüklü tentelerin kurulumu ve kullanıma kolay tente modellerinden sadece biridir. Tente Sistemi Akordeon Şeklinde Açılıp Kapanmaktadır Diğer Tentelerde Farkı yan kısımlar Kapalı olduğundan Güneş ve Yağmur gelmesini Engeller  kullanıldığı alanlarda şık Dizaynı ve Tasarımıyla bulunduğu alana ayrı bir Görsellik katar.\r\n\r\nKörüklü Sisteminin Saçak Modeli Deniz dalgası modeli veya Düz saçak modeli tercih edilmektedir.",
                            Name = "Körük Tente",
                            Price = 2500m,
                            Slug = "koruk-tente"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Comment = "Stor tente normal mafsallı tentenin kolsuz modelidir.karşıdan gelen güneş için tercih edilen bir modeldir. Stor tente Yukardan aşağı açılıp kapanan bir modeldir istenildiği taktirde motorlu sistemde uyumludur.stor tente asıl amacı, gölgelendirme işlevini yapmak olsa da fonksiyonellik yönünden de hiçbir şekilde sınır tanımamaktadır.",
                            Name = "Stor Tente",
                            Price = 1500m,
                            Slug = "stor-tente"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Comment = "Çift açılır tente kurulumu ve kullanımı kolay tente modellerinden sadece biridir.\r\n\r\nBu tente sayesinde hem daha sağlıklı bir hava ortamına sahip olursunuz hemde iş yerleriniz daha güzel bire görünüme kavuşmaktadır. taksitli fiyatları akrilik kumaşlı ısı geçirmeyen garanti belgeli kaliteli",
                            Name = "Çift Açılır Tente",
                            Price = 5000m,
                            Slug = "cift-acılır-tente"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir.",
                            Name = "Mafsallı Tente",
                            Price = 30000m,
                            Slug = "mafsalli-tente"
                        });
                });

            modelBuilder.Entity("Entities.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsMain = true,
                            MediaId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsMain = false,
                            MediaId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsMain = true,
                            MediaId = 4,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 5,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 6,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 7,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 8,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 9,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 10,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 11,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 3,
                            IsMain = false,
                            MediaId = 12,
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("Entities.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Firmamız satış dışında Teknik Servisleri montaj hizmeti de vermektedir. Ayrıca kurulmuş olan yapıları yeni yerinize en uygun şekilde uyarlayarak kurulum hizmetini de sunmaktayız.",
                            Name = "Teknik Servis",
                            Slug = "teknik-servis"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Firmamız satış dışında Teknik Servisleri montaj hizmeti de vermektedir. Ayrıca kurulmuş olan yapıları yeni yerinize en uygun şekilde uyarlayarak kurulum hizmetini de sunmaktayız.",
                            Name = "Teknik Özellikler",
                            Slug = "teknik-ozellikler"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Firmamız satış dışında Teknik Servisleri montaj hizmeti de vermektedir. Ayrıca kurulmuş olan yapıları yeni yerinize en uygun şekilde uyarlayarak kurulum hizmetini de sunmaktayız.",
                            Name = "Blackout Pergola Tente Kumaşı",
                            ParentId = 2,
                            Slug = "blackout-pergola-tente-kumasi"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Firmamız satış dışında Teknik Servisleri montaj hizmeti de vermektedir. Ayrıca kurulmuş olan yapıları yeni yerinize en uygun şekilde uyarlayarak kurulum hizmetini de sunmaktayız.",
                            Name = "Pergola Tente Teknik Özellikleri",
                            ParentId = 2,
                            Slug = "pergola-tente-teknik-ozellikleri"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Firmamız satış dışında Teknik Servisleri montaj hizmeti de vermektedir. Ayrıca kurulmuş olan yapıları yeni yerinize en uygun şekilde uyarlayarak kurulum hizmetini de sunmaktayız.",
                            Name = "Pergola Tente İmalatı Çeşitleri",
                            ParentId = 2,
                            Slug = "pergola-tente-imalati-cesitleri"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Firmamız satış dışında Teknik Servisleri montaj hizmeti de vermektedir. Ayrıca kurulmuş olan yapıları yeni yerinize en uygun şekilde uyarlayarak kurulum hizmetini de sunmaktayız.",
                            Name = "Kullanım Özellikleri",
                            Slug = "kullanim-ozellikleri"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Firmamız satış dışında Teknik Servisleri montaj hizmeti de vermektedir. Ayrıca kurulmuş olan yapıları yeni yerinize en uygun şekilde uyarlayarak kurulum hizmetini de sunmaktayız.",
                            Name = "Projeler",
                            Slug = "projeler"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Firmamız satış dışında Teknik Servisleri montaj hizmeti de vermektedir. Ayrıca kurulmuş olan yapıları yeni yerinize en uygun şekilde uyarlayarak kurulum hizmetini de sunmaktayız.",
                            Name = "Faydalı Bilgiler",
                            Slug = "faydali-bilgiler"
                        });
                });

            modelBuilder.Entity("Entities.Models.ServiceImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MediaId = 3,
                            ServiceId = 1
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Models.ProductImage", b =>
                {
                    b.HasOne("Entities.Models.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Models.Service", b =>
                {
                    b.HasOne("Entities.Models.Service", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Entities.Models.ServiceImage", b =>
                {
                    b.HasOne("Entities.Models.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Service", "Service")
                        .WithMany("Images")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Entities.Models.Service", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
