using Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Repositories.Config
{
    public class ProductConfig : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> builder)
        {
            builder.HasKey(p => p.Id);
            builder.Property(p => p.Name).IsRequired();
            builder.Property(p => p.Slug).IsRequired();



            builder.HasData(

                //tente sitemleri
                new Product() { Id = 1, CategoryId = 2, Name = "Pergole Tente", Slug = "pergole-tente", Price = null, Comment = "Pergole Tenteler Ticari alanlarda veya konutlarda kullanılan pergole tente sistemleri, dış mekanda yaşam kalitesini yükselten ekipmanlardan oluşur. Çok uzun yıllar boyunca kullanılan pergole tente, hava koşullarına karşı en ideal yaşam alanları oluşturmayı sağlar. Bu sistemler teknolojik gelişmelerle birlikte güncellenip motor ve sensör desteğiyle daha kullanışlı hale gelmiştir. İşyeriniz veya eviniz için ihtiyacınız olan tüm pergola tenteleri firmamızdan uygun fiyatlarla tedarik edebilirsiniz. " },
                new Product() { Id = 2, CategoryId = 2, Name = "Körük Tente", Slug = "koruk-tente", Price = null, Comment = "Körüklü tentelerin kurulumu ve kullanıma kolay tente modellerinden sadece biridir. Tente Sistemi Akordeon Şeklinde Açılıp Kapanmaktadır Diğer Tentelerde Farkı yan kısımlar Kapalı olduğundan Güneş ve Yağmur gelmesini Engeller  kullanıldığı alanlarda şık Dizaynı ve Tasarımıyla bulunduğu alana ayrı bir Görsellik katar.\r\n\r\nKörüklü Sisteminin Saçak Modeli Deniz dalgası modeli veya Düz saçak modeli tercih edilmektedir." },
                new Product() { Id = 3, CategoryId = 2, Name = "Stor Tente", Slug = "stor-tente", Price = null, Comment = "Stor tente normal mafsallı tentenin kolsuz modelidir.karşıdan gelen güneş için tercih edilen bir modeldir. Stor tente Yukardan aşağı açılıp kapanan bir modeldir istenildiği taktirde motorlu sistemde uyumludur.stor tente asıl amacı, gölgelendirme işlevini yapmak olsa da fonksiyonellik yönünden de hiçbir şekilde sınır tanımamaktadır." },
                new Product() { Id = 4, CategoryId = 2, Name = "Çift Açılır Tente", Slug = "cift-acılır-tente", Price = null, Comment = "Çift açılır tente kurulumu ve kullanımı kolay tente modellerinden sadece biridir.\r\n\r\nBu tente sayesinde hem daha sağlıklı bir hava ortamına sahip olursunuz hemde iş yerleriniz daha güzel bire görünüme kavuşmaktadır. taksitli fiyatları akrilik kumaşlı ısı geçirmeyen garanti belgeli kaliteli" },
                new Product() { Id = 5, CategoryId = 2, Name = "Mafsallı Tente", Slug = "mafsalli-tente", Price = null, Comment = "Mafsallı tente gerek kış aylarında oluşabilecek olumsuz hava koşullarından korunmak gerekse yazın güneşten kaçınmak için yaptırılan kurulumu ve kullanıma kolay bir tente modelidir." },

                //giyotincam
                new Product()
                {
                    Id = 6,
                    CategoryId = 1,
                    Name = "Giyotin Cam",
                    Slug = "giyotin-cam",
                    Price = null,
                    Comment = "Giyotin cam sistemleri, özellikle teras, balkon, kış bahçesi ve geniş cephe uygulamalarında şık, kullanışlı ve modern bir çözümdür. Üstten ya da alttan raylar üzerinde dikey olarak kayan cam paneller sayesinde açıklık tamamen açılabilir ya da istenirse tamamen kapanabilir." +
                               "Cam panellerin pürüzsüz kayışıyla yüksek manevra kabiliyeti sunar.Isı, ses ve rüzgâr yalıtımında etkili çözümler sağlar.Minimal profil tasarımıyla görüş alanını geniş tutar, mekâna ferahlık katar.Üstten kilit mekanizmaları ve güvenlik cam seçenekleriyle güvenli kullanım sunar.Farklı açılı uygulamalara (örneğin çatı çıkıntıları veya yüksek cepheler) adaptasyon imkânı verir.Giyotin cam sistemleri, hem estetik hem teknik açıdan yükselen bir tercih olarak dış mekânların yaşam alanına dönüşmesine katkı sağlar."
                },
                new Product() { Id = 7, CategoryId = 1, Name = "Fotoselli Giyotin Cam Kapı", Slug = "fotoselli-giyotin-cam-kapi", Price = null, Comment = "Fotoselli giyotin cam kapı sistemleri, modern mimarinin şık görünümünü ileri düzey teknolojiyle birleştiren otomatik kapı çözümleridir. Dikey hareketli cam paneller, sensör (fotosel) yardımıyla kişi veya araç algılandığında otomatik olarak açılıp kapanır. Bu sayede hem kullanım kolaylığı hem de enerji verimliliği sağlar." },

                //branda sistemleri
                new Product() { Id = 8, CategoryId = 3, Name = "Şeffaf Kış Bahçesi", Slug = "seffaf-kıs-bahcesi", Price = null, Comment = "Şeffaf kış bahçesi brandası, açık alanları dört mevsim kullanılabilir hale getiren en pratik ve ekonomik çözümlerden biridir. Soğuk, rüzgâr, yağmur ve kar gibi dış etkenlerden korunmak için tasarlanan bu sistem, mekanın doğal ışığını kesmeden mükemmel bir koruma sağlar." },
                new Product() { Id = 9, CategoryId = 3, Name = "Şeffaf Alan Kapama", Slug = "seffaf-alan-kapama", Price = null, Comment = "Şeffaf alan kapama sistemleri, açık alanları dış etkenlerden koruyarak dört mevsim kullanılabilir hale getiren modern çözümlerdir. Yüksek kaliteli şeffaf PVC malzemeden üretilen bu brandalar, hem dayanıklı hem de estetik bir kullanım sunar. Mekânın doğal ışığını engellemeden koruma sağlar; böylece iç mekânlar ferahlığını kaybetmeden dış ortam koşullarına karşı korunur." },
                new Product() { Id = 10, CategoryId = 3, Name = "Şeffaf Pvc Mika Branda", Slug = "seffaf-pvc-mika-branda", Price = null, Comment = "Şeffaf PVC Mika branda, dış mekânları her mevsim konforlu ve kullanışlı hale getiren modern koruma sistemlerinden biridir. Tam şeffaf yapısı sayesinde dış ortamla görsel bağlantıyı kesmeden, yağmur, rüzgâr, toz ve soğuk gibi olumsuz hava koşullarına karşı mükemmel koruma sağlar." },
                new Product() { Id = 11, CategoryId = 3, Name = "Havuz Brandası", Slug = "havuz-brandasi", Price = null, Comment = "Havuz brandası, yüzme havuzlarını dış etkenlerden korumak, güvenliği artırmak ve temizlik maliyetlerini düşürmek için geliştirilen dayanıklı bir kaplama sistemidir. Mevsimsel kullanıma uygun olan bu brandalar, hem açık hem de kapalı havuzlarda estetik ve fonksiyonel bir çözüm sunar." },
                new Product() { Id = 12, CategoryId = 3, Name = "İskele Brandası", Slug = "iskele-brandasi", Price = null, Comment = "İskele brandası, inşaat ve tadilat alanlarında güvenliği sağlamak, çevreyi korumak ve estetik bir görünüm oluşturmak amacıyla kullanılan özel bir koruma sistemidir. Dayanıklı PVC veya polietilen (PE) malzemeden üretilen iskele brandaları, hem çalışanların hem de çevredeki insanların güvenliğini artırırken, yapı alanını dış etkenlerden korur." },
                new Product() { Id = 13, CategoryId = 3, Name = "Kamelya Branda", Slug = "kamelya-branda", Price = null, Comment = "Kamelya brandası, açık alanlarda bulunan kamelya, çardak ve oturma alanlarını dört mevsim koruma altına almak için tasarlanmış şık ve dayanıklı bir kaplama sistemidir. Estetik görünümü, uzun ömürlü malzemesi ve hava koşullarına karşı yüksek direnci sayesinde konforlu bir dış mekân deneyimi sunar." },
                new Product() { Id = 14, CategoryId = 3, Name = "Pazar Brandası", Slug = "pazar-brandasi", Price = null, Comment = "Pazar brandası, açık alanlarda kurulan pazar yerleri, tezgâhlar ve satış alanlarını güneş, yağmur, rüzgâr gibi dış etkenlerden korumak için özel olarak üretilen dayanıklı kaplama sistemidir. Hafif yapısı, kolay kurulumu ve uzun ömürlü malzemesi sayesinde esnaflar ve organizasyon alanları için pratik bir çözümdür." },
                new Product() { Id = 15, CategoryId = 3, Name = "Reklam Brandası", Slug = "reklam-brandasi", Price = null, Comment = "Reklam brandası, markanı veya işletmeni geniş kitlelere tanıtmak için kullanılan en etkili ve ekonomik açık hava reklam çözümlerinden biridir. Dayanıklı branda kumaşı üzerine yüksek çözünürlüklü dijital baskı uygulanarak üretilen bu sistemler, hem iç hem de dış mekânlarda uzun süreli görünürlük sağlar." },
                new Product() { Id = 16, CategoryId = 3, Name = "Araç Koruma Brandası", Slug = "arac-koruma-brandasi", Price = null, Comment = "Araç koruma brandası, otomobilleri güneş, yağmur, dolu, kar, kuş pisliği, toz ve ağaç reçinesi gibi dış etkenlerden korumak için özel olarak tasarlanmış pratik bir örtü sistemidir. Dayanıklı, su geçirmez ve UV ışınlarına karşı dirençli yapısı sayesinde aracınızın dış yüzeyini her mevsim güvenle korur." },
                new Product() { Id = 17, CategoryId = 3, Name = "Yat ve Tekne Brandası", Slug = "yat-tekne-brandasi", Price = null, Comment = "Yat ve tekne brandası, deniz taşıtlarını güneş, tuzlu su, yağmur, rüzgâr ve kuş pisliği gibi dış etkenlerden korumak için özel olarak tasarlanmış dayanıklı bir koruma sistemidir. Su geçirmez, UV dayanımlı ve uzun ömürlü kumaş yapısı sayesinde teknenizi yıl boyunca güvenle muhafaza eder." },
                // cam sistemleri
                new Product() { Id = 18, CategoryId = 4, Name = "Cam Balkon", Slug = "cam-balkon", Price = null, Comment = "Cam balkon sistemleri, balkonları dört mevsim kullanılabilir hale getiren, modern, estetik ve fonksiyonel bir kaplama çözümüdür. Isı, ses ve rüzgâr yalıtımı sağlayan bu sistemler, mekânın mimarisine değer katarken yaşam alanlarına da konfor kazandırır." },
                new Product() { Id = 19, CategoryId = 4, Name = "Cam Veranda", Slug = "cam-veranda", Price = null, Comment = "Cam veranda sistemleri, açık alanları modern, estetik ve korunaklı yaşam alanlarına dönüştüren şık mimari çözümlerden biridir. Dört mevsim kullanılabilen yapısıyla verandanı hem yağmurdan hem rüzgârdan korur; aynı zamanda ferah, aydınlık ve konforlu bir ortam oluşturur." },

                // cadır sitemleri
                new Product() { Id = 20, CategoryId = 5, Name = "Depo Çadırı", Slug = "depo-cadiri", Price = null, Comment = "Depo çadırı, sanayi, tarım ve lojistik sektörlerinde malzeme, ürün ve ekipmanların güvenli bir şekilde korunması için tasarlanmış, dayanıklı ve ekonomik bir kapalı alan çözümüdür. Hızlı kurulumu, taşınabilir yapısı ve uzun ömürlü malzemesi sayesinde kalıcı binalara alternatif olarak sıkça tercih edilir." },
                new Product() { Id = 21, CategoryId = 5, Name = "Doğal Afet Çadırı", Slug = "dogal-afet-cadiri", Price = null, Comment = "Doğal afet çadırı, deprem, sel, yangın, fırtına veya diğer acil durumlarda barınma ihtiyacını hızlı bir şekilde karşılamak üzere tasarlanmış, dayanıklı ve pratik kurulumlu geçici yaşam alanıdır. Zorlu hava koşullarına dayanıklı yapısı ve kolay taşınabilirliği sayesinde, afet bölgelerinde en güvenilir barınma çözümlerinden biridir." },
                new Product() { Id = 22, CategoryId = 5, Name = "Halı Saha Çadırı", Slug = "hali -saha-cadiri", Price = null, Comment = "Halı saha çadırı, açık veya kapalı spor alanlarını dört mevsim kullanılabilir hale getiren, dayanıklı ve estetik bir kaplama sistemidir. Spor tesisleri için özel olarak tasarlanan bu yapılar; hava koşullarına karşı tam koruma sağlarken, aynı zamanda modern ve ferah bir oyun ortamı sunar." },
                new Product() { Id = 23, CategoryId = 5, Name = "Hayvan Besi Çadırı", Slug = "hayvan-besi-cadiri", Price = null, Comment = "Hayvan besi çadırı, büyükbaş ve küçükbaş hayvanların barınma, beslenme ve üretim süreçlerinde kullanılan, dayanıklı ve ekonomik bir barınak çözümüdür. Hızlı kurulumu, geniş iç hacmi ve uzun ömürlü yapısıyla modern hayvancılık işletmeleri için ideal bir seçenektir." },
                new Product() { Id = 24, CategoryId = 5, Name = "Spor Kompleksi Çadırı", Slug = "spor-kompleksi-cadiri", Price = null, Comment = "Spor kompleksi çadırı, kapalı veya yarı kapalı spor alanlarını dört mevsim kullanılabilir hale getiren modern, dayanıklı ve ekonomik çözümlerden biridir. Hızlı kurulumu, uzun ömürlü yapısı ve estetik tasarımı sayesinde farklı spor dallarına uygun, geniş ve ferah bir oyun alanı oluşturur." },
                new Product() { Id = 25, CategoryId = 5, Name = "Şantiye Çadırı", Slug = "santiye-cadiri", Price = null, Comment = "Şantiye çadırı, inşaat ve saha çalışmalarında personel, malzeme ve ekipmanların korunması için kullanılan pratik, dayanıklı ve ekonomik barınma çözümlerinden biridir. Hızlı kurulumu, taşınabilir yapısı ve uzun ömürlü malzemesi sayesinde her türlü zemin ve iklim koşulunda güvenli kullanım sağlar." },
                new Product() { Id = 26, CategoryId = 5, Name = "Kiralık Çadır", Slug = "kiralik-cadir", Price = null, Comment = "Kiralık çadır sistemleri, kısa süreli organizasyon, etkinlik, fuar, düğün, inşaat veya geçici depolama ihtiyaçları için en pratik ve ekonomik çözümlerden biridir. Dayanıklı yapısı, kolay kurulumu ve taşınabilirliği sayesinde farklı sektörlerde güvenle kullanılabilir." },
                new Product() { Id = 27, CategoryId = 5, Name = "Konser Tören Çadırı", Slug = "konser-toren-cadiri", Price = null, Comment = "Konser ve tören çadırı sistemleri, açık alan etkinliklerinde hava koşullarından etkilenmeden güvenli, konforlu ve estetik bir organizasyon ortamı oluşturmak için tasarlanmış modern çözümlerdir. Dayanıklı yapısı, geniş alan kaplama kapasitesi ve şık tasarımıyla her türlü etkinliğe profesyonel bir görünüm kazandırır." },
                //Sineklik sitemleri
                new Product() { Id = 28, CategoryId = 6, Name = "Sürgülü Sineklik", Slug = "surgulu-sineklik", Price = null, Comment = "Sürgülü sineklik sistemleri, pencere ve kapılarda havalandırma konforunu bozmadan sinek, böcek ve haşerelere karşı etkili koruma sağlayan pratik çözümlerdir. Şık tasarımı, kolay kullanımı ve uzun ömürlü yapısıyla modern yaşam alanlarının vazgeçilmez bir parçasıdır." },
                //giyotin cam estra ürünler
                new Product() { Id = 29, CategoryId = 1, Name = "Motorlu Giyotin Cam", Slug = "motorlu-giyotin-cam", Price = null, Comment = "Motorlu giyotin cam sistemleri, modern mimarinin en şık ve işlevsel çözümlerinden biridir. Dikey hareketle çalışan otomatik cam paneller, uzaktan kumanda veya buton yardımıyla kolayca açılıp kapanabilir. Bu sayede mekanlarda estetik, konfor ve teknolojiyi bir arada sunar." },
                new Product() { Id = 30, CategoryId = 1, Name = "Üstte Toplanır Giyotin Cam", Slug = "ustte-toplanır-giyotin-cam", Price = null, Comment = "Üstte toplanır giyotin cam sistemleri, modern mimaride estetik ve konforu bir araya getiren yenilikçi bir cam kapama çözümüdür. Dikey hareketli paneller, özel motor sistemi sayesinde yukarı doğru toplanarak açık alanların pratik şekilde kontrol edilmesini sağlar. Kafe, restoran, otel, veranda ve teraslarda sıklıkla tercih edilir." },
                new Product() { Id = 31, CategoryId = 1, Name = "Silinebilir Giyotin Cam", Slug = "silinebilir-giyotin-cam", Price = null, Comment = "Silinebilir giyotin cam sistemleri, modern yapılarda estetik görünüm, konfor ve kolay bakım avantajlarını bir arada sunan yenilikçi bir cam kaplama çözümüdür. Dikey hareketli cam paneller, özel mekanizması sayesinde kolayca temizlenebilir ve bakım gerektirmeden uzun yıllar kullanılabilir." },
                new Product() { Id = 32, CategoryId = 1, Name = "Isı Camlı Giyotin", Slug = "isi-camli-giyotin", Price = null, Comment = "Isı camlı giyotin cam sistemleri, modern mimarinin zarif tasarımını yüksek ısı yalıtımıyla birleştiren yenilikçi bir cam kapama çözümüdür. Dikey hareketli cam paneller, uzaktan kumanda veya buton yardımıyla kolayca kontrol edilirken, çift cam teknolojisi sayesinde hem enerji tasarrufu hem de konfor sağlar." },
                new Product() { Id = 33, CategoryId = 1, Name = "Tek Camlı Giyotin", Slug = "tek-camli-giyotin", Price = null, Comment = "Tek camlı giyotin sistemleri, modern mimarinin zarif çizgilerini pratik kullanım ve ekonomik çözümlerle birleştiren yenilikçi cam kapama sistemleridir. Dikey hareketle çalışan cam paneller, motorlu veya manuel mekanizma sayesinde kolayca açılıp kapanabilir. Şeffaf, estetik ve hafif yapısıyla hem konut hem de ticari alanlarda sıkça tercih edilir." },
                new Product() { Id = 34, CategoryId = 1, Name = "Kumandalı Giyotin Cam", Slug = "kumandali-giyotin-cam", Price = null, Comment = "Kumandalı giyotin cam sistemleri, modern yaşam alanlarında konfor, güvenlik ve estetiği bir araya getiren yenilikçi bir cam kaplama çözümüdür. Uzaktan kumanda veya buton yardımıyla kolayca kontrol edilen dikey hareketli cam paneller, açık alanları dilediğin gibi yönetme özgürlüğü sunar." },

                //cam sitemlirei estra ürünler
                new Product() { Id = 35, CategoryId = 4, Name = "Katlanır Cam Balkon", Slug = "katlanir-cam-balkon", Price = null, Comment = "Katlanır cam balkon sistemleri, modern yaşam alanlarında estetik, konfor ve fonksiyonelliği bir araya getiren en popüler cam kapama çözümlerinden biridir. Cam panellerin yana doğru katlanarak tamamen açılabilmesi, balkonları ve terasları dört mevsim kullanılabilir hale getirir." },
                new Product() { Id = 36, CategoryId = 4, Name = "Açılır Cam Tavan Sistemleri", Slug = "acilir-cam-tavan-sistemleri", Price = null, Comment = "Açılır cam tavan sistemleri, iç mekânlara doğal ışık kazandırırken dış etkenlerden korunmayı sağlayan modern ve estetik mimari çözümlerden biridir. Uzaktan kumanda veya manuel mekanizma ile kolayca açılıp kapanabilen bu sistemler, yaşam alanlarını dört mevsim kullanılabilir hale getirir." },
                new Product() { Id = 37, CategoryId = 4, Name = "Cam Çatı Sistemleri", Slug = "cam-cati-sistemleri", Price = null, Comment = "Cam çatı sistemleri, mimaride şeffaflık ve doğal ışığı ön plana çıkaran modern bir kaplama çözümüdür. Dayanıklı yapısı ve estetik görünümüyle hem konutlarda hem de ticari yapılarda tercih edilir. Geniş açıklıkları kapatarak mekânlara ferahlık kazandıran bu sistemler, dört mevsim konforu bir arada sunar." },
                // tente sistemleri estra ürünler
                new Product() { Id = 38, CategoryId = 2, Name = "Motorlu Tente", Slug = "motorlu-tente", Price = null, Comment = "Motorlu tente sistemleri, modern yaşam alanlarında konfor, estetik ve işlevselliği bir araya getiren en pratik gölgelendirme çözümlerinden biridir. Uzaktan kumanda, buton veya sensör desteğiyle kolayca açılıp kapanan bu sistemler, güneşten, yağmurdan ve rüzgârdan koruma sağlayarak açık alanları dört mevsim kullanılabilir hale getirir." },
                new Product() { Id = 39, CategoryId = 2, Name = "Sabit Tente", Slug = "sabit-tente", Price = null, Comment = "Sabit tente sistemleri, dayanıklılığı ve estetik görünümüyle uzun yıllar boyunca koruma sağlayan en klasik ve güvenilir gölgelendirme çözümlerinden biridir. Yapıya sabit şekilde monte edilen bu tenteler, her türlü hava koşuluna karşı koruma sunarken mekânlara modern bir görünüm kazandırır." },
                new Product() { Id = 40, CategoryId = 2, Name = "Kumandalı Tente", Slug = "kumandali-tente", Price = null, Comment = "Kumandalı tente sistemleri, modern yaşam alanlarında konforu ve estetiği bir araya getiren en gelişmiş gölgelendirme çözümlerinden biridir. Uzaktan kumanda veya buton yardımıyla kolayca açılıp kapanabilen bu sistemler, hem kullanıcı dostu yapısı hem de şık tasarımıyla açık alanları dört mevsim kullanılabilir hale getirir." },
                new Product() { Id = 41, CategoryId = 2, Name = "Rolling Roof Tente", Slug = "rolling-roof-tente", Price = null, Comment = "Rolling Roof tente sistemleri, modern mimarinin en yenilikçi dış mekân çözümlerinden biridir. Açılır-kapanır tavan yapısı sayesinde tam gölgelendirme, havalandırma ve koruma sunan bu sistem, hem estetik hem de teknolojik yapısıyla yaşam alanlarını dört mevsim kullanılabilir hale getirir." },
                new Product() { Id = 42, CategoryId = 2, Name = "Bio Klimatik Tente", Slug = "bio-klimatik-tente", Price = null, Comment = "Biyoklimatik tente sistemleri, doğa ile uyumlu şekilde tasarlanmış, modern yaşam alanlarına konfor ve estetik kazandıran ileri teknoloji gölgelendirme çözümleridir. Alüminyum panellerin açılıp kapanabilen yapısı sayesinde güneş ışığını, havayı ve yağmuru kontrollü şekilde yönlendirir; böylece açık alanlar dört mevsim kullanılabilir hale gelir." }





                );
        }
    }
}
